### ISSUE TITLE
Site not responding Thanks to me GOODLUCK DEBUGGING

### ISSUE THREAD

**Issue by Developerayo** [Fremerinc/Tasksify#3]
So the site does not work anymore 👍 . GoodLuck Fixing It. 😄

**Comment by BolajiAyodeji** [comment]
Damn!
Would fix @Developerayo

**Comment by BolajiAyodeji** [comment]
Fixed @Developerayo 
Issue closing!

**Comment by Developerayo** [comment]
Good Job

**Comment by Developerayo** [comment]
Give me a minute so I can spoile something else and you fix. :fire:
